#!/bin/sh

##
# Runit run script for postgresql
#

# If the database has been persisted in a volume, it may need
# permissions setting.
chown -R postgres /var/www/postgresql/ || exit 1

exec /sbin/setuser postgres /usr/lib/postgresql/9.3/bin/postgres \
    -D /var/www/postgresql/9.3/main \
    -c config_file=/etc/postgresql/9.3/main/postgresql.conf
